version: '3'

services:

  mysql:
    image: mysql:8.0
    ports:
      - 3307:3307
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rasplus
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data_container:/data/db

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rasmoo
      MONGO_INITDB_ROOT_PASSWORD: senha123
    ports:
      - 27017:27017
    volumes:
      - mongo_data_container:/data/db

volumes:
  mysql_data_container:
  mongo_data_container: